### PR TITLE
Fixes some layout bugs in iOS 8 with the iPhone 6

### LINKED ISSUE #192: iOS 8 Layout issue when leaving ViewController
When leaving a view controller, we see that the view under the navigation is too wide.
Navigation bug

### PR DESCRIPTION
**Pull request by feliciaan**
Also fixes #192

### CODE REVIEW

File: iOS/Hydra/PreferencesController.m [hunk 1]
```diff
@@ -104,7 +104,8 @@ - (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(N
                     cell.textLabel.text = @"Toon alle verenigingen";
                     cell.detailTextLabel.text = @"";
 
-                    CGRect toggleRect = CGRectMake(225, 9, 0, 0);
+                    CGFloat screen_width = self.view.frame.size.width;
```
Comment (Javache) [inline iOS/Hydra/PreferencesController.m]: Use camelCase consistently, so `screenWidth`.
